import fs from "node:fs/promises";
import path from "node:path";
import { formatDate } from "@/lib/utils";

function cleanText(value: unknown, fallback = "Not provided") {
  if (typeof value !== "string") return fallback;
  const cleaned = value.replace(/\s+/g, " ").trim();
  return cleaned || fallback;
}

function list(values: string[], fallback = "- Not available") {
  const cleaned = values.map((value) => value.trim()).filter(Boolean);
  return cleaned.length ? cleaned.map((value) => `- ${value}`).join("\n") : fallback;
}

function safeDate(value: unknown) {
  try {
    return formatDate(value as string);
  } catch {
    return "Date not available";
  }
}

function safeFileName(value: string) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 52);
}

export function buildLawyerHandoffMarkdown(legalCase: any) {
  const documents = Array.isArray(legalCase.documents) ? legalCase.documents : [];
  const evidenceItems = Array.isArray(legalCase.evidenceItems) ? legalCase.evidenceItems : [];
  const timelineEvents = Array.isArray(legalCase.timelineEvents) ? legalCase.timelineEvents : [];
  const deadlines = Array.isArray(legalCase.deadlines) ? legalCase.deadlines : [];
  const drafts = Array.isArray(legalCase.drafts) ? legalCase.drafts : [];
  const assignments = Array.isArray(legalCase.assignments) ? legalCase.assignments : [];

  const acceptedLawyers = assignments
    .filter((item: any) => item.status === "ACCEPTED")
    .map((item: any) => item.lawyer?.user?.name || "Accepted lawyer");

  return [
    `# Lawyer Handoff Packet: ${cleanText(legalCase.title, "Untitled case")}`,
    "Generated by MIZAN from the current workspace record. Review before relying on it.",
    "## Matter Snapshot",
    `- Category: ${cleanText(legalCase.category)}`,
    `- Status: ${cleanText(legalCase.status)}`,
    `- Stage: ${cleanText(legalCase.stage)}`,
    `- Priority: ${cleanText(legalCase.priority)}`,
    `- Client: ${cleanText(legalCase.client?.user?.name)}`,
    `- Accepted lawyer(s): ${acceptedLawyers.join(", ") || "Not assigned yet"}`,
    "## Client Narrative",
    cleanText(legalCase.description, "No case description has been entered yet."),
    "## Evidence Index",
    list(
      documents.map((document: any) => {
        const category = document.probableCategory ? ` (${document.probableCategory})` : "";
        return `${document.fileName}${category}: ${cleanText(document.aiSummary, "Summary pending")}`;
      })
    ),
    "## Evidence Items",
    list(
      evidenceItems.map((item: any) => `${item.label}: ${cleanText(item.summary, item.searchableText || "No summary")}`)
    ),
    "## Chronology",
    list(
      timelineEvents.map((event: any) => {
        const source = event.sourceLabel ? ` [${event.sourceLabel}]` : "";
        return `${safeDate(event.eventDate)} - ${event.title}${source}: ${cleanText(event.description, "")}`;
      })
    ),
    "## Deadlines",
    list(
      deadlines.map((deadline: any) => {
        const notes = deadline.notes ? ` - ${deadline.notes}` : "";
        return `${safeDate(deadline.dueDate)} - ${deadline.title} (${deadline.status}, ${deadline.importance})${notes}`;
      })
    ),
    "## Drafts",
    list(drafts.map((draft: any) => `${draft.title} (${draft.type}, ${draft.verificationStatus})`)),
    "## Lawyer Review Questions",
    list([
      "Which legal route is strongest on the available facts?",
      "What facts or documents are missing before notice, complaint, or filing?",
      "Are there urgent deadlines, limitation concerns, or interim protections to verify?",
      "What evidence should be preserved immediately?"
    ])
  ].join("\n\n");
}

export function buildCourtReadyBundleMarkdown(legalCase: any, includePrivateNotes = false) {
  const documents = Array.isArray(legalCase.documents) ? legalCase.documents : [];
  const timelineEvents = Array.isArray(legalCase.timelineEvents) ? legalCase.timelineEvents : [];
  const deadlines = Array.isArray(legalCase.deadlines) ? legalCase.deadlines : [];
  const drafts = Array.isArray(legalCase.drafts) ? legalCase.drafts : [];
  const notes = includePrivateNotes && Array.isArray(legalCase.internalNotes) ? legalCase.internalNotes : [];

  return [
    `# Court-Ready Bundle: ${cleanText(legalCase.title, "Untitled case")}`,
    "This bundle is a workspace-generated organizer. A lawyer should review it before court use.",
    "## Cover Sheet",
    `- Case: ${cleanText(legalCase.title, "Untitled case")}`,
    `- Client: ${cleanText(legalCase.client?.user?.name)}`,
    `- Category: ${cleanText(legalCase.category)}`,
    `- Status: ${cleanText(legalCase.status)}`,
    `- Prepared: ${formatDate(new Date().toISOString())}`,
    "## Case Summary",
    cleanText(legalCase.description, "No case description has been entered yet."),
    "## Chronology for Pleadings",
    list(
      timelineEvents.map((event: any, index: number) => {
        return `${index + 1}. ${safeDate(event.eventDate)} - ${event.title}: ${cleanText(event.description, "")}`;
      })
    ),
    "## Document and Evidence Annexure Index",
    list(
      documents.map((document: any, index: number) => {
        const confidence = document.confidence ? `, AI confidence ${Math.round(document.confidence * 100)}%` : "";
        return `Annex ${index + 1}: ${document.fileName} (${document.mimeType}${confidence})`;
      })
    ),
    "## Deadline Table",
    list(
      deadlines.map((deadline: any) => `${safeDate(deadline.dueDate)} - ${deadline.title} (${deadline.status})`)
    ),
    "## Drafts and Editable Pleadings",
    list(drafts.map((draft: any) => `${draft.title} - ${draft.type} - ${draft.verificationStatus}`)),
    includePrivateNotes
      ? ["## Lawyer-Only Internal Notes", list(notes.map((note: any) => cleanText(note.body, "")))].join("\n\n")
      : "",
    "## Readiness Checklist",
    list([
      "Verify parties' full legal names and addresses.",
      "Verify dates, amounts, and document authenticity.",
      "Confirm jurisdiction and forum with a licensed lawyer.",
      "Attach only documents that are relevant and safe to disclose."
    ])
  ]
    .filter(Boolean)
    .join("\n\n");
}

export async function writeMarkdownPacket(input: {
  caseId: string;
  title: string;
  kind: string;
  markdown: string;
}) {
  const outputDir = path.join(process.cwd(), "public", "exports");
  await fs.mkdir(outputDir, { recursive: true });

  const fileName = `${safeFileName(input.kind)}-${safeFileName(input.title || input.caseId)}-${Date.now()}.md`;
  const absolutePath = path.join(outputDir, fileName);
  await fs.writeFile(absolutePath, input.markdown, "utf8");

  return {
    absolutePath,
    publicPath: `/exports/${fileName}`
  };
}
